[directory]
style = "dimmed blue"
truncation_length = 3
truncate_to_repo = true

[character]
success_symbol = "[âœ¨](dimmed yellow)"
error_symbol = "[âœ—](bold red)"

[git_status]
conflicted = "ğŸ’¥"
ahead = "ğŸš€${count}"
behind = "ğŸŒ${count}"
diverged = "ğŸ”€${ahead_count}${behind_count}"
untracked = "â“"
stashed = "ğŸ“š"
modified = "âœï¸"
staged = "[âœ…$count](green)"
renamed = "ğŸ“›"
deleted = "ğŸ—‘ï¸"

[nodejs]
symbol = "â¬¢ "
style = "bold green"

[python]
symbol = "ğŸ "
style = "bold blue"

[rust]
symbol = "ğŸ¦€ "
style = "bold red"

[java]
symbol = "â˜• "
style = "bold red"

[golang]
symbol = "ğŸ¹ "
style = "bold cyan"

[docker_context]
symbol = "ğŸ‹ "
style = "blue bold"

[username]
show_always = false
style_user = "bold cyan"
style_root = "bold red"

[hostname]
ssh_only = true
format = "[$hostname](bold red) "

[cmd_duration]
min_time = 2_000
format = "took [$duration](bold yellow)"
